### ISSUE TITLE
Project status?!?

### ISSUE THREAD

**Issue by jedie** [divio/djangocms-rest-api#13]
What's the project status now? Is this project alive? Last commit is from dec.2016...

**Comment by FinalAngel** [comment]
@jedie you are very welcome to contribute. We're looking for people who test, fix and suggest improvements.

**Comment by jedie** [comment]
I just wonder that nothing happen since dec.2016:

1. The project is abandoned, maybe because it's not practical...
2. The project is ready for production and just works...

**Comment by FinalAngel** [comment]
There is still lots to do before we recommend using it in production and it hasn't been released yet. Development is in progress (https://github.com/divio/djangocms-rest-api/pull/12). We are happy for help and additional contributors.
